---
run:
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - ineffassign
    - interfacer
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
    # - errcheck
    # - gochecknoglobals
    # - gocyclo
    # - golint
    # - gosec
    # - govet
    # - lll
    # - maligned
    # - nakedret
    # - prealloc
    # - scopelint
    # - unconvert
    # - unparam
issues:
  exclude:
    - .*_Ctype_security_context_t.*
linters-settings:
  gocritic:
    enabled-checks:
      # Diagnostic
      - argOrder
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - flagName
      - nilValReturn
      - offBy1
      - weakCond
      # - appendAssign
      # - octalLiteral
      # - sloppyReassign

      # Performance
      - equalFold
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy
      # - appendCombine
      # - hugeParam

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - yodaStyleExpr
      # - wrapperFunc

      # Opinionated
      - initClause
      - nestingReduce
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock
      # - builtinShadow
      # - importShadow
      # - paramTypeCombine
      # - unnamedResult
